-- MySQL Script generated by MySQL Workbench
-- Fri May 19 20:20:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfil` (
  `idPerfil` INT NOT NULL,
  `Detalle` VARCHAR(45) NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `idPerfil` INT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `FechaCreacion` DATETIME NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `Perfil_idx` (`idPerfil` ASC),
  CONSTRAINT `Perfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `mydb`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PostEstado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PostEstado` (
  `idPostEstado` INT NOT NULL,
  `Detalle` VARCHAR(45) NULL,
  PRIMARY KEY (`idPostEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `idPost` INT NOT NULL,
  `idUsuario` INT NULL,
  `Titulo` VARCHAR(200) NULL,
  `Cuerpo` TEXT NULL,
  `idPostEstado` INT NULL,
  `FechaCreacion` DATETIME NULL,
  PRIMARY KEY (`idPost`),
  INDEX `Usuario_idx` (`idUsuario` ASC),
  INDEX `PostEstado_idx` (`idPostEstado` ASC),
  CONSTRAINT `PostEstado`
    FOREIGN KEY (`idPostEstado`)
    REFERENCES `mydb`.`PostEstado` (`idPostEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ComentarioEstado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ComentarioEstado` (
  `idComentarioEstado` INT NOT NULL,
  `Detalle` VARCHAR(45) NULL,
  PRIMARY KEY (`idComentarioEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT NOT NULL,
  `idUsuario` INT NULL,
  `idPost` INT NULL,
  `Comentario` TEXT NULL,
  `idComentarioEstado` INT NULL,
  `FechaCreacion` DATETIME NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `Post_idx` (`idPost` ASC),
  INDEX `Usuario_idx` (`idUsuario` ASC),
  INDEX `ComentarioEstado_idx` (`idComentarioEstado` ASC),
  CONSTRAINT `Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Post`
    FOREIGN KEY (`idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ComentarioEstado`
    FOREIGN KEY (`idComentarioEstado`)
    REFERENCES `mydb`.`ComentarioEstado` (`idComentarioEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
